# $NetBSD$

DISTNAME=	importlib-1.0.3
PKGNAME=	${PYPKGPREFIX}-${DISTNAME}
CATEGORIES=	devel lang python
MASTER_SITES=	${MASTER_SITE_PYPI:=i/importlib/}

MAINTAINER=	nils@NetBSD.org
HOMEPAGE=	https://pypi.python.org/pypi/importlib/
COMMENT=	Backport of importlib.import_module() from Python 2.7
LICENSE=	python-software-foundation

USE_LANGUAGES=	# none

.include "../../lang/python/egg.mk"
.include "../../mk/bsd.pkg.mk"
